/** Aligns with genny `voiceFormOptions` / Inworld publish gender. */
export const VOICE_DESIGN_GENDERS = ['male', 'female', 'neutral'] as const;

/** Aligns with genny `VOICE_AGE_OPTIONS`. */
export const VOICE_DESIGN_AGES = [
  'young',
  'young_adult',
  'early_middle_aged',
  'late_middle_aged',
  'senior',
] as const;

/** Aligns with genny `VOICE_ACCENT_OPTIONS` (ElevenLabs accent labels). */
export const VOICE_DESIGN_ACCENTS = [
  'American',
  'Australian',
  'British',
  'Canadian',
  'Indian',
  'Irish',
  'Jamaican',
  'New Zealand',
  'Nigerian',
  'Scottish',
  'South African',
  'African American',
  'Singaporean',
  'US - Boston',
  'US - Chicago',
  'US - New York',
  'US - Southern',
  'US - Midwest',
  'US - Northeast',
  'Cockney',
  'Geordie',
  'Received Pronunciation',
  'Scouse',
  'Welsh',
  'Yorkshire',
  'Arabic',
  'Bulgarian',
  'Chinese',
  'Croatian',
  'Czech',
  'Danish',
  'Dutch',
  'Filipino',
  'Finnish',
  'French',
  'German',
  'Greek',
  'Hindi',
  'Indonesian',
  'Italian',
  'Japanese',
  'Korean',
  'Malay',
  'Polish',
  'Portuguese',
  'Romanian',
  'Russian',
  'Slovak',
  'Spanish',
  'Swedish',
  'Tamil',
  'Turkish',
  'Ukrainian',
] as const;
